package main

import (
	"flag"
	"fmt"
	"os"
	"strings"
	"text/template"
)

var (
	serviceTypeName  = flag.String("type", "", `-type="Type"`)
	fileTemplate     = template.Must(template.New("file").Parse(fileTemplateContent))
	testfileTemplate = template.Must(template.New("testfile").Parse(testFileContent))
	fileNameTmpl     = "%s_service_gen.go"
	testfileNameTmpl = "%s_service_gen_test.go"
)

func main() {
	flag.Parse()
	if *serviceTypeName == "" {
		fmt.Printf("No service given. Aborting...\n")
		os.Exit(1)
	}
	fname := fmt.Sprintf(fileNameTmpl, strings.ToLower(*serviceTypeName))
	file, err := os.Create(fname)
	if err != nil {
		fmt.Printf("There was an error creating the file: %s\n", fname)
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	err = fileTemplate.Execute(file, *serviceTypeName)
	if err != nil {
		fmt.Printf("There was an error parsing the given file template.\n")
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	fname = fmt.Sprintf(testfileNameTmpl, strings.ToLower(*serviceTypeName))
	file, err = os.Create(fname)
	if err != nil {
		fmt.Printf("There was an error creating the file: %s\n", fname)
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
	err = testfileTemplate.Execute(file, *serviceTypeName)
	if err != nil {
		fmt.Printf("There was an error parsing the given file template.\n")
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}
}

var fileTemplateContent = `// DO NOT EDIT!
// This file is generated by the api generator.
package harvest

import (
	"net/url"
)

type {{.}}Service struct {
	api Api
}

func New{{.}}Service(api Api) *{{.}}Service {
	service := {{.}}Service{api: api}
	return &service
}

func (s *{{.}}Service) All(users *[]*{{.}}, params url.Values) error {
	return s.api.All(users, params)
}

func (s *{{.}}Service) Find(id int, user *{{.}}, params url.Values) error {
	return s.api.Find(id, user, params)
}

func (s *{{.}}Service) Create(user *{{.}}) error {
	return s.api.Create(user)
}

func (s *{{.}}Service) Update(user *{{.}}) error {
	return s.api.Update(user)
}

func (s *{{.}}Service) Delete(user *{{.}}) error {
	return s.api.Delete(user)
}
`

var testFileContent = `// DO NOT EDIT!
// This file is generated by the api generator.
package harvest

import (
	"net/url"
	"reflect"
	"testing"
)

type testFunc func(*apiWrapperTestData, *bool) Api

var (
	expectedParams = url.Values{"foo": []string{"bar"}}

	tests = map[string]struct { // apiFn to testData
		testData *apiWrapperTestData
		testFn   testFunc
		args     []interface{}
	}{
		"All": {
			&apiWrapperTestData{
				expectedParams:       expectedParams,
				expectedDataType:     reflect.TypeOf(&[]*{{.}}{}),
				expectedErrorMessage: "ERR",
			},
			testApiAllWrapper,
			[]interface{}{&[]*{{.}}{}, expectedParams},
		},
		"Find": {
			&apiWrapperTestData{
				expectedParams:       expectedParams,
				expectedIdType:       reflect.TypeOf(12),
				expectedDataType:     reflect.TypeOf(&{{.}}{}),
				expectedErrorMessage: "ERR",
			},
			testApiFindWrapper,
			[]interface{}{12, &{{.}}{}, expectedParams},
		},
		"Create": {
			&apiWrapperTestData{
				expectedDataType:     reflect.TypeOf(&{{.}}{}),
				expectedErrorMessage: "ERR",
			},
			testApiCreateWrapper,

			[]interface{}{&{{.}}{}},
		},
		"Update": {
			&apiWrapperTestData{
				expectedDataType:     reflect.TypeOf(&{{.}}{}),
				expectedErrorMessage: "ERR",
			},
			testApiUpdateWrapper,

			[]interface{}{&{{.}}{}},
		},
		"Delete": {
			&apiWrapperTestData{
				expectedDataType:     reflect.TypeOf(&{{.}}{}),
				expectedErrorMessage: "ERR",
			},
			testApiDeleteWrapper,

			[]interface{}{&{{.}}{}},
		},
	}
)

func Test{{.}}ServiceAll(t *testing.T) {
	testServiceMethod(t, "All")
}

func Test{{.}}ServiceFind(t *testing.T) {
	testServiceMethod(t, "Find")
}

func Test{{.}}ServiceCreate(t *testing.T) {
	testServiceMethod(t, "Create")
}

func Test{{.}}ServiceUpdate(t *testing.T) {
	testServiceMethod(t, "Update")
}

func Test{{.}}ServiceDelete(t *testing.T) {
	testServiceMethod(t, "Delete")
}

func testServiceMethod(t *testing.T, name string) {
	called := false
	test, ok := tests[name]
	if !ok {
		t.Logf("No test data for method '%s' defined.\n", name)
		t.FailNow()
	}
	api := test.testFn(test.testData, &called)
	service := New{{.}}Service(api)
	serviceValue := reflect.ValueOf(service)
	testFn := serviceValue.MethodByName(name)
	if !testFn.IsValid() {
		t.Logf("Expected service to have method '%s', had not.\n", name)
		t.FailNow()
	}

	var args []reflect.Value
	for _, v := range test.args {
		args = append(args, reflect.ValueOf(v))
	}
	res := testFn.Call(args)

	if !called {
		t.Logf("Expected Api.%s method to have been called, was not.\n", name)
		t.Fail()
	}

	errors := test.testData.getErrors()

	if errors != "" {
		t.Logf("Found errors:\n%s", errors)
		t.Fail()
	}

	err := res[0]
	if err.IsNil() {
		t.Logf("Expected error not to be nil\n")
		t.Fail()
	}

	if !err.IsNil() {
		expectedMessage := "ERR"
		actualMessage := err.MethodByName("Error").Call([]reflect.Value{})[0].String()
		if expectedMessage != actualMessage {
			t.Logf("Expected error to have message '%q', got '%q'\n", expectedMessage, actualMessage)
			t.Fail()
		}
	}
}
`
