// DO NOT EDIT!
// This file is generated by the api generator.
package harvest

import (
	"net/url"
)

type ProjectService struct {
	api CrudTogglerApi
}

func NewProjectService(api CrudTogglerApi) *ProjectService {
	service := ProjectService{api: api}
	return &service
}

func (s *ProjectService) All(users *[]*Project, params url.Values) error {
	return s.api.All(users, params)
}

func (s *ProjectService) Find(id int, user *Project, params url.Values) error {
	return s.api.Find(id, user, params)
}

func (s *ProjectService) Create(user *Project) error {
	return s.api.Create(user)
}

func (s *ProjectService) Update(user *Project) error {
	return s.api.Update(user)
}

func (s *ProjectService) Delete(user *Project) error {
	return s.api.Delete(user)
}

func (s *ProjectService) Toggle(user *Project) error {
	return s.api.Toggle(user)
}
