// DO NOT EDIT!
// This file is generated by the api generator.

// +build !integration

package harvest

import (
	"net/url"
)

type ProjectService struct {
	endpoint CrudTogglerEndpoint
}

func NewProjectService(endpoint CrudTogglerEndpoint) *ProjectService {
	service := ProjectService{
		endpoint: endpoint,
	}
	return &service
}

func (s *ProjectService) All(projects *[]*Project, params url.Values) error {
	return s.endpoint.All(projects, params)
}

func (s *ProjectService) Find(id int, project *Project, params url.Values) error {
	return s.endpoint.Find(id, project, params)
}

func (s *ProjectService) Create(project *Project) error {
	return s.endpoint.Create(project)
}

func (s *ProjectService) Update(project *Project) error {
	return s.endpoint.Update(project)
}

func (s *ProjectService) Delete(project *Project) error {
	return s.endpoint.Delete(project)
}

func (s *ProjectService) Toggle(project *Project) error {
	return s.endpoint.Toggle(project)
}
