// DO NOT EDIT!
// This file is generated by the api generator.
package harvest

import (
	"net/url"
	"reflect"
	"testing"
)

type testFunc func(*apiWrapperTestData, *bool) Api

var (
	expectedParams = url.Values{"foo": []string{"bar"}}

	tests = map[string]struct { // apiFn to testData
		testData *apiWrapperTestData
		testFn   testFunc
		args     []interface{}
	}{
		"All": {
			&apiWrapperTestData{
				expectedParams:       expectedParams,
				expectedDataType:     reflect.TypeOf(&[]*User{}),
				expectedErrorMessage: "ERR",
			},
			testApiAllWrapper,
			[]interface{}{&[]*User{}, expectedParams},
		},
		"Find": {
			&apiWrapperTestData{
				expectedParams:       expectedParams,
				expectedIdType:       reflect.TypeOf(12),
				expectedDataType:     reflect.TypeOf(&User{}),
				expectedErrorMessage: "ERR",
			},
			testApiFindWrapper,
			[]interface{}{12, &User{}, expectedParams},
		},
		"Create": {
			&apiWrapperTestData{
				expectedDataType:     reflect.TypeOf(&User{}),
				expectedErrorMessage: "ERR",
			},
			testApiCreateWrapper,

			[]interface{}{&User{}},
		},
		"Update": {
			&apiWrapperTestData{
				expectedDataType:     reflect.TypeOf(&User{}),
				expectedErrorMessage: "ERR",
			},
			testApiUpdateWrapper,

			[]interface{}{&User{}},
		},
		"Delete": {
			&apiWrapperTestData{
				expectedDataType:     reflect.TypeOf(&User{}),
				expectedErrorMessage: "ERR",
			},
			testApiDeleteWrapper,

			[]interface{}{&User{}},
		},
	}
)

func TestUserServiceAll(t *testing.T) {
	testServiceMethod(t, "All")
}

func TestUserServiceFind(t *testing.T) {
	testServiceMethod(t, "Find")
}

func TestUserServiceCreate(t *testing.T) {
	testServiceMethod(t, "Create")
}

func TestUserServiceUpdate(t *testing.T) {
	testServiceMethod(t, "Update")
}

func TestUserServiceDelete(t *testing.T) {
	testServiceMethod(t, "Delete")
}

func testServiceMethod(t *testing.T, name string) {
	called := false
	test, ok := tests[name]
	if !ok {
		t.Logf("No test data for method '%s' defined.\n", name)
		t.FailNow()
	}
	api := test.testFn(test.testData, &called)
	service := NewUserService(api)
	serviceValue := reflect.ValueOf(service)
	testFn := serviceValue.MethodByName(name)
	if !testFn.IsValid() {
		t.Logf("Expected service to have method '%s', had not.\n", name)
		t.FailNow()
	}

	var args []reflect.Value
	for _, v := range test.args {
		args = append(args, reflect.ValueOf(v))
	}
	res := testFn.Call(args)

	if !called {
		t.Logf("Expected Api.%s method to have been called, was not.\n", name)
		t.Fail()
	}

	errors := test.testData.getErrors()

	if errors != "" {
		t.Logf("Found errors:\n%s", errors)
		t.Fail()
	}

	err := res[0]
	if err.IsNil() {
		t.Logf("Expected error not to be nil\n")
		t.Fail()
	}

	if !err.IsNil() {
		expectedMessage := "ERR"
		actualMessage := err.MethodByName("Error").Call([]reflect.Value{})[0].String()
		if expectedMessage != actualMessage {
			t.Logf("Expected error to have message '%q', got '%q'\n", expectedMessage, actualMessage)
			t.Fail()
		}
	}
}
